# Django secrets.
SECRET_KEY = '<DEFAULT>'

# Google credentials
GOOGLE_ANALYTICS_PROPERTY_ID = '<DEFAULT>'
GOOGLE_ANALYTICS_DOMAIN = '<DEFAULT>'
RECAPTCHA_PUBLIC_KEY = '<DEFAULT>'
RECAPTCHA_PRIVATE_KEY = '<DEFAULT>'

# Email credentials
EMAIL_HOST_USER = '<DEFAULT>'
EMAIL_HOST_PASSWORD = '<DEFAULT>'


